Make Slf4jThreadLocalAccessor loadable by ServiceLoader
Slf4jThreadLocalAccessor were not loaded by ServiceLoader
because it does not have a public, no-arg constructor, producing the
following exception:

java.util.ServiceConfigurationError: io.micrometer.context.ThreadLocalAccessor: io.micrometer.context.integration.Slf4jThreadLocalAccessor Unable to get public no-arg constructor

Closes gh-540